import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, BookOpen, CheckCircle2, ChevronRight, Eye, EyeOff, FileText, GraduationCap, Lock, Sparkles, TrendingUp } from "lucide-react";
import { demoAssignment, rubricRows, studentAssignments } from "../data/workflowData";
import { StatusBadge } from "../components/WorkflowUI";
import "./StudentPortal.css";

function StudentShell({ children }) { return <div className="student-shell"><header className="student-topbar"><Link to="/student/dashboard" className="student-brand"><span><Sparkles size={18}/></span><b>EvalAI</b><small>STUDENT PORTAL</small></Link><div className="student-profile"><div>RP</div><span><strong>Rahul Patil</strong><small>ENTC Engineering</small></span></div></header><main>{children}</main></div> }

export function StudentLogin() { const [show, setShow] = useState(false); const navigate = useNavigate(); return <div className="student-login"><div className="student-login-aside"><Link to="/" className="student-back"><ArrowLeft size={15}/> Back to Home</Link><div><span className="student-login-tag"><GraduationCap size={14}/> EVALAI STUDENT PORTAL</span><h1>Stay informed.<br/><em>Learn with clarity.</em></h1><p>Track assignment progress, access released evaluation feedback, and understand your academic performance.</p><ul><li><CheckCircle2 size={16}/> View assessment outcomes</li><li><CheckCircle2 size={16}/> Understand approved feedback</li><li><CheckCircle2 size={16}/> Track academic progress</li></ul></div><small>EvalAI Academic Assessment Platform · Student Access</small></div><section className="student-login-main"><div className="student-login-card"><div className="student-login-icon"><GraduationCap size={24}/></div><h2>Student Login</h2><p>Sign in to access your assignments and results.</p><div className="student-demo"><Lock size={15}/><span><b>Demo Access Enabled</b> · rahul.patil@college.edu</span></div><form onSubmit={(event)=>{event.preventDefault();navigate("/student/dashboard")}}><label>College Email / Student ID<input defaultValue="rahul.patil@college.edu" required/></label><label>Password<div className="student-password"><input type={show?"text":"password"} defaultValue="studentdemo" required/><button type="button" onClick={()=>setShow(!show)} aria-label="Toggle password visibility">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><button className="student-login-btn">Sign In to Student Portal</button></form><small className="student-login-note">Access is restricted to enrolled students.</small></div></section></div> }

export function StudentDashboard() { const navigate = useNavigate(); return <StudentShell><div className="student-page"><header className="student-welcome"><div><span>ACADEMIC OVERVIEW</span><h1>Welcome back, Rahul</h1><p>Here is a snapshot of your current assessment activity.</p></div><div className="student-performance"><TrendingUp size={18}/><span>Current performance</span><strong>84.5%</strong></div></header><div className="student-stat-grid">{[["Assigned Work","3","1 due this week"],["Recent Submissions","5","All on time"],["Evaluation Status","2","1 result released"],["Average Score","84.5%","+4.0% this term"]].map(([a,b,c])=><div key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div><div className="student-content-grid"><section className="student-surface student-assignment-list"><div className="student-section-heading"><div><span>ASSIGNED WORK</span><h2>Your assignments</h2></div><BookOpen size={19}/></div>{studentAssignments.map((item)=><article key={item.id}><div><h3>{item.title}</h3><p>{item.course} · {item.due}</p></div><div><StatusBadge status={item.status}/>{item.status === "Result Released" ? <button onClick={()=>navigate("/student/results/dsp-a03")}>View Result <ChevronRight size={14}/></button> : <button>View Assignment <ChevronRight size={14}/></button>}</div></article>)}</section><aside className="student-side"><section className="student-surface"><div className="student-section-heading"><div><span>AI FEEDBACK SUMMARY</span><h2>Latest released feedback</h2></div></div><p className="student-feedback">You explain sampling and aliasing accurately. To improve further, include the anti-aliasing filter and a clearer Nyquist-rate justification.</p><button onClick={()=>navigate("/student/results/dsp-a03")}>Open released result <ChevronRight size={14}/></button></section><section className="student-surface student-deadlines"><div className="student-section-heading"><div><span>UPCOMING DEADLINES</span><h2>Plan ahead</h2></div></div><div><b>18 Aug</b><span>Signals & Systems — Assignment 02<small>Due at 11:59 PM</small></span></div><div><b>22 Aug</b><span>Microcontrollers — Lab Assignment 05<small>Due at 5:00 PM</small></span></div></section></aside></div><section className="student-surface student-trend"><div className="student-section-heading"><div><span>PERFORMANCE TREND</span><h2>Assessment progress</h2></div><FileText size={18}/></div><div className="trend-bars">{[72,78,85,84].map((value,index)=><div key={index}><i style={{height:`${value}%`}}/><span>A{index+1}</span></div>)}</div></section></div></StudentShell> }

export function StudentResult() { return <StudentShell><div className="student-page"><Link className="student-back-result" to="/student/dashboard"><ArrowLeft size={15}/> Back to Dashboard</Link><header className="student-result-header"><div><span>RELEASED RESULT</span><h1>{demoAssignment.title}</h1><p>Teacher-approved feedback for Rahul Patil · ET202-041</p></div><div className="student-score"><strong>17 <small>/ 20</small></strong><span>85% · Grade A</span></div></header><div className="student-result-grid"><section className="student-surface"><div className="student-section-heading"><div><span>RUBRIC BREAKDOWN</span><h2>Your assessment outcome</h2></div></div>{rubricRows.map((item)=><div className="student-rubric" key={item.name}><div><strong>{item.name}</strong><p>{item.reason}</p></div><b>{item.score} / {item.max}</b></div>)}</section><aside className="student-side"><section className="student-surface student-feedback-full"><span>TEACHER-APPROVED FEEDBACK</span><h2>Good conceptual foundation</h2><p>Your explanation of sampling and aliasing is correct and well structured. For future responses, add the role of the anti-aliasing filter and support the Nyquist condition with mathematical notation.</p></section><section className="student-surface"><span>LEARNING RECOMMENDATIONS</span><ul><li>Review the sampling theorem derivation.</li><li>Practice identifying aliasing in frequency-domain plots.</li><li>Revise anti-aliasing filters before the next assignment.</li></ul></section></aside></div></div></StudentShell> }
